/**
 * Seed data for the CoreDesk workspace.
 *
 * Representative sample records — not client data. Shaped to the record model in
 * the architecture board and the page inventory:
 *
 *   Client  -> Projects, Contacts, access grants
 *   Project -> Tasks, Milestones, Documents, Files
 *   Document -> immutable Versions -> Review requests -> one designated approver
 *   Delivery package -> exact approved versions
 *
 * The workspace state is seeded once into localStorage and then mutated by the
 * app, so every screen reads and writes the same records.
 */

import type {
  AccessGrant, ActivityEvent, Client, DeliveryPackage, DocumentRecord,
  ProjectFile, Project, Review, Task, Workspace,
} from './types';

export const seedWorkspace: Workspace = {
  id: 'ws-northlight',
  name: 'Northlight Studio',
  ownerName: 'Anas Ayari',
  ownerEmail: 'anas@northlight.studio',
  timezone: 'Europe/Amsterdam (GMT+2)',
  services: [
    { id: 'sv-1', name: 'Brand identity system', basis: 'Fixed fee', amount: 12400, currency: 'EUR' },
    { id: 'sv-2', name: 'Website design', basis: 'Fixed fee', amount: 9800, currency: 'EUR' },
    { id: 'sv-3', name: 'Design system', basis: 'Day rate', amount: 780, currency: 'EUR' },
    { id: 'sv-4', name: 'Consultation', basis: 'Hourly', amount: 120, currency: 'EUR' },
  ],
  business: {
    website: 'northlight.studio',
    registration: '',
    logoLabel: 'logo-primary.svg',
    accent: '#2F6FEB',
  },
  proposalDefaults: {
    includeFeeTable: true,
    includeAssumptions: true,
    includePaymentTerms: false,
  },
};

export const seedClients: Client[] = [
  {
    id: 'cl-harbor',
    name: 'Harbor & Finch',
    state: 'active',
    brandColor: '#2563eb',
    website: 'harborfinch.com',
    industry: 'Retail & Lifestyle',
    tier: 'retainer',
    totalBilled: 14500,
    currency: 'USD',
    contacts: [
      { id: 'ct-1', name: 'Marta Velasco', role: 'Marketing Director', email: 'marta@harborfinch.com', primary: true },
      { id: 'ct-2', name: 'Tomas Reiner', role: 'Operations Lead', email: 'tomas@harborfinch.com', primary: false },
    ],
    nextAction: 'Review requested on brand guidelines v3',
    nextActionTone: 'waiting',
    nextActionDue: '2026-09-12',
    lastActivity: '2026-09-09T16:40:00',
    privateNote: 'Retainer conversation due after the site launches. Prefers Friday check-ins.',
  },
  {
    id: 'cl-verity',
    name: 'Verity Health',
    state: 'active',
    brandColor: '#059669',
    website: 'verityhealth.io',
    industry: 'Healthcare Tech',
    tier: 'fixed',
    totalBilled: 8200,
    currency: 'USD',
    contacts: [{ id: 'ct-3', name: 'Anil Kapoor', role: 'Founder', email: 'anil@verityhealth.io', primary: true }],
    nextAction: 'Send revised proposal',
    nextActionTone: 'risk',
    nextActionDue: '2026-09-06',
    lastActivity: '2026-09-04T11:05:00',
    privateNote: 'Waiting on their legal review of the data-processing annex.',
  },
  {
    id: 'cl-atlas',
    name: 'Atlas Coffee Roasters',
    state: 'active',
    brandColor: '#d97706',
    website: 'atlasroasters.co',
    industry: 'Food & Beverage',
    tier: 'fixed',
    totalBilled: 5400,
    currency: 'USD',
    contacts: [{ id: 'ct-4', name: 'Priya Nandakumar', role: 'Co-owner', email: 'priya@atlasroasters.co', primary: true }],
    nextAction: 'Awaiting scope acceptance',
    nextActionTone: 'waiting',
    nextActionDue: '2026-09-14',
    lastActivity: '2026-09-08T09:15:00',
    privateNote: 'Second location opening in November — packaging needed before then.',
  },
  {
    id: 'cl-northgate',
    name: 'Northgate Legal',
    state: 'prospect',
    brandColor: '#4f46e5',
    website: 'northgate.legal',
    industry: 'Professional Services',
    tier: 'retainer',
    totalBilled: 0,
    currency: 'USD',
    contacts: [{ id: 'ct-5', name: 'Elena Sokolova', role: 'Partner', email: 'e.sokolova@northgate.legal', primary: true }],
    nextAction: 'Discovery call notes to send',
    nextActionTone: 'accent',
    nextActionDue: '2026-09-15',
    lastActivity: '2026-09-07T14:30:00',
    privateNote: 'Referred by Harbor & Finch. Cautious about client-facing document access.',
  },
  {
    id: 'cl-lumen',
    name: 'Lumen Architects',
    state: 'inactive',
    brandColor: '#6b7280',
    website: 'lumenarch.com',
    industry: 'Architecture',
    tier: 'hourly',
    totalBilled: 11800,
    currency: 'EUR',
    contacts: [{ id: 'ct-6', name: 'Sofia Brandt', role: 'Studio Manager', email: 'sofia@lumenarch.com', primary: true }],
    nextAction: 'No open work',
    nextActionTone: 'neutral',
    nextActionDue: null,
    lastActivity: '2026-06-22T10:00:00',
    privateNote: 'Wayfinding project closed in June. Revisit for signage phase in 2027.',
  },
  {
    id: 'cl-tidewater',
    name: 'Tidewater Foundation',
    state: 'archived',
    contacts: [{ id: 'ct-7', name: 'Grace Okonkwo', role: 'Programme Lead', email: 'grace@tidewater.org', primary: true }],
    nextAction: 'Archived record — read-only',
    nextActionTone: 'neutral',
    nextActionDue: null,
    lastActivity: '2026-03-30T12:00:00',
    privateNote: 'Archived at client request. Access revoked separately.',
    archivedOn: '2026-04-14',
  },
];

export const seedProjects: Project[] = [
  {
    id: 'pr-identity',
    name: 'Brand identity system',
    clientId: 'cl-harbor',
    outcome: 'A complete identity system the team can apply without asking us.',
    stage: 'in-review',
    due: '2026-09-19',
    nextMilestone: 'Guidelines approved',
    nextMilestoneDue: '2026-09-12',
    nextAction: 'Review requested on brand guidelines v3',
    nextActionTone: 'waiting',
    brief:
      'Harbor & Finch are repositioning from regional supplier to national specialty brand. The identity must survive long print runs, work at 16px in a procurement PDF and hold up on a trade-stand wall.',
    inScope: [
      'Wordmark and responsive logo lockups',
      'Colour and typography system',
      'Application guidelines (24 pages)',
      'Packaging and trade-stand applications',
    ],
    outOfScope: ['Website build (separate engagement)', 'Photography production', 'Print management and press checks'],
    scopeAccepted: true,
    scopeAcceptedOn: '2026-07-18',
    startedOn: '2026-07-21',
    milestones: [
      { id: 'ms-1', name: 'Direction signed off', due: '2026-08-08', done: true },
      { id: 'ms-2', name: 'System applied to packaging', due: '2026-09-05', done: true },
      { id: 'ms-3', name: 'Guidelines approved', due: '2026-09-12', done: false },
      { id: 'ms-4', name: 'Handover and delivery', due: '2026-09-19', done: false },
    ],
  },
  {
    id: 'pr-onboarding',
    name: 'Patient onboarding redesign',
    clientId: 'cl-verity',
    outcome: 'Cut onboarding drop-off by making the first ten minutes obvious.',
    stage: 'planned',
    due: '2026-10-02',
    nextMilestone: 'Proposal accepted',
    nextMilestoneDue: '2026-09-06',
    nextAction: 'Send revised proposal',
    nextActionTone: 'risk',
    brief:
      "Verity's intake form loses most patients at the insurance step. This engagement scopes the research and redesign of the first-run experience only.",
    inScope: ['Intake research synthesis', 'Revised onboarding flow', 'Component specification'],
    outOfScope: ['Engineering implementation', 'Backend or claims integration'],
    scopeAccepted: false,
    scopeAcceptedOn: null,
    startedOn: '2026-08-28',
    milestones: [
      { id: 'ms-5', name: 'Proposal accepted', due: '2026-09-06', done: false },
      { id: 'ms-6', name: 'Research complete', due: '2026-09-22', done: false },
    ],
  },
  {
    id: 'pr-site',
    name: 'Website design',
    clientId: 'cl-harbor',
    outcome: 'A marketing site that converts trade enquiries.',
    stage: 'planned',
    due: '2026-11-14',
    nextMilestone: 'Kick-off',
    nextMilestoneDue: '2026-09-26',
    nextAction: 'Confirm kick-off date',
    nextActionTone: 'accent',
    brief: 'Phase two of the Harbor & Finch work, deliberately sequenced after the identity system lands.',
    inScope: ['Sitemap and wireframes', 'High-fidelity page design', 'Design system handoff'],
    outOfScope: ['Build and CMS implementation'],
    scopeAccepted: true,
    scopeAcceptedOn: '2026-08-30',
    startedOn: null,
    milestones: [{ id: 'ms-7', name: 'Kick-off', due: '2026-09-26', done: false }],
  },
  {
    id: 'pr-packaging',
    name: 'Retail packaging range',
    clientId: 'cl-atlas',
    outcome: 'Shelf-ready packaging for the second location.',
    stage: 'on-hold',
    due: '2026-10-24',
    nextMilestone: 'Scope accepted',
    nextMilestoneDue: '2026-09-14',
    nextAction: 'Awaiting scope acceptance',
    nextActionTone: 'waiting',
    brief: 'Five-SKU retail range for the new location, using the existing roast-profile visual language.',
    inScope: ['Packaging structure', 'Label artwork', 'Print specification'],
    outOfScope: ['Photography', 'Print buying'],
    scopeAccepted: false,
    scopeAcceptedOn: null,
    startedOn: null,
    milestones: [{ id: 'ms-8', name: 'Scope accepted', due: '2026-09-14', done: false }],
  },
  {
    id: 'pr-wayfinding',
    name: 'Gallery wayfinding',
    clientId: 'cl-lumen',
    outcome: 'Signage system for the riverside gallery.',
    stage: 'closed',
    due: '2026-06-19',
    nextMilestone: 'Delivered',
    nextMilestoneDue: '2026-06-19',
    nextAction: 'Closed — delivery acknowledged',
    nextActionTone: 'ok',
    brief: 'Wayfinding and room signage for the new riverside gallery wing.',
    inScope: ['Signage system', 'Installation drawings'],
    outOfScope: ['Fabrication and install'],
    scopeAccepted: true,
    scopeAcceptedOn: '2026-03-11',
    startedOn: '2026-03-16',
    milestones: [{ id: 'ms-9', name: 'Delivered', due: '2026-06-19', done: true }],
  },
];

export const seedTasks: Task[] = [
  {
    id: 'tk-1',
    title: 'Send revised proposal with staged payment schedule',
    projectId: 'pr-onboarding',
    clientId: 'cl-verity',
    due: '2026-09-06',
    status: 'todo',
    priority: 'high',
    milestoneId: 'ms-5',
    note: 'Anil asked for the fee split across three milestones instead of two.',
    checklist: [
      { id: 'ci-1', text: 'Rebuild fee table', done: true },
      { id: 'ci-2', text: 'Confirm milestone dates with Anil', done: false },
      { id: 'ci-3', text: 'Regenerate PDF and attach', done: false },
    ],
  },
  {
    id: 'tk-2',
    title: 'Chase Harbor & Finch on guidelines review',
    projectId: 'pr-identity',
    clientId: null,
    due: '2026-09-11',
    status: 'in-progress',
    attention: 'waiting',
    priority: 'medium',
    milestoneId: 'ms-3',
    note: 'Request sent 3 Sept. Marta returns from leave on the 11th.',
    checklist: [],
  },
  {
    id: 'tk-3',
    title: 'Export packaging artwork at press resolution',
    projectId: 'pr-identity',
    clientId: null,
    due: '2026-09-10',
    status: 'in-progress',
    priority: 'high',
    milestoneId: 'ms-2',
    note: 'CMYK conversion for the two spot colours.',
    dependencies: ['tk-1'],
    blockedByTaskId: 'tk-1',
    checklist: [
      { id: 'ci-4', text: 'Convert to CMYK', done: true },
      { id: 'ci-5', text: 'Check total ink coverage', done: true },
      { id: 'ci-6', text: 'Export press-ready PDFs', done: false },
    ],
  },
  {
    id: 'tk-4',
    title: 'Prepare kick-off agenda for website design',
    projectId: 'pr-site',
    clientId: null,
    due: '2026-09-24',
    status: 'todo',
    priority: 'low',
    milestoneId: 'ms-7',
    note: '',
    checklist: [],
  },
  {
    id: 'tk-5',
    title: 'Archive Verity discovery recordings',
    projectId: 'pr-onboarding',
    clientId: null,
    due: '2026-09-09',
    status: 'todo',
    priority: 'low',
    milestoneId: null,
    note: 'Keep recordings out of the shared project surface.',
    checklist: [],
  },
  {
    id: 'tk-6',
    title: 'Confirm second-location opening date',
    projectId: 'pr-packaging',
    clientId: null,
    due: '2026-09-16',
    status: 'todo',
    attention: 'waiting',
    priority: 'medium',
    milestoneId: 'ms-8',
    note: 'Blocks the print schedule.',
    checklist: [],
  },
  {
    id: 'tk-7',
    title: 'Apply type scale to packaging labels',
    projectId: 'pr-identity',
    clientId: null,
    due: '2026-09-04',
    status: 'done',
    priority: 'medium',
    milestoneId: 'ms-2',
    note: '',
    checklist: [],
  },
  {
    id: 'tk-8',
    title: 'Write guidelines section on clear space',
    projectId: 'pr-identity',
    clientId: null,
    due: '2026-09-02',
    status: 'done',
    priority: 'medium',
    milestoneId: 'ms-2',
    note: '',
    checklist: [],
  },
  {
    id: 'tk-9',
    title: 'Record scope acceptance for website design',
    projectId: 'pr-site',
    clientId: null,
    due: '2026-08-30',
    status: 'done',
    priority: 'low',
    milestoneId: null,
    note: '',
    checklist: [],
  },
  {
    id: 'tk-10',
    title: 'Send discovery call notes to Northgate Legal',
    projectId: null,
    clientId: 'cl-northgate',
    due: '2026-09-15',
    status: 'todo',
    priority: 'medium',
    milestoneId: null,
    note: 'Not yet a project — belongs to the client record until scope is agreed.',
    checklist: [],
  },
];

export const seedDocuments: DocumentRecord[] = [
  {
    id: 'doc-guidelines',
    title: 'Brand guidelines',
    type: 'Deliverable',
    clientId: 'cl-harbor',
    projectId: 'pr-identity',
    workingVersion: 4,
    submittedVersion: 3,
    reviewState: 'waiting',
    visibility: 'shared',
    sections: ['Positioning', 'Wordmark', 'Clear space and minimum size', 'Colour', 'Typography', 'Applications', 'Contact'],
    internalNote: 'Hold the motion section until the packaging range is signed off.',
    modified: '2026-09-09T16:40:00',
    versions: [
      { n: 3, author: 'Nadia Rahman', date: '2026-09-03T10:12:00', decision: null, note: 'Sent for review with the clear-space section rewritten.' },
      { n: 2, author: 'Nadia Rahman', date: '2026-08-19T15:30:00', decision: 'changes', note: 'Client asked for a wider colour range.' },
      { n: 1, author: 'Nadia Rahman', date: '2026-08-06T09:05:00', decision: 'changes', note: 'First submitted draft.' },
    ],
  },
  {
    id: 'doc-proposal-verity',
    title: 'Proposal — onboarding redesign',
    type: 'Proposal',
    clientId: 'cl-verity',
    projectId: 'pr-onboarding',
    workingVersion: 2,
    submittedVersion: 1,
    reviewState: 'changes-requested',
    visibility: 'private',
    sections: ['Context', 'Objectives', 'Scope', 'Deliverables', 'Schedule', 'Fees', 'Assumptions'],
    internalNote: 'Fee split needs rebuilding to three milestones before this goes out.',
    modified: '2026-09-04T11:05:00',
    versions: [
      { n: 1, author: 'Nadia Rahman', date: '2026-08-28T13:00:00', decision: 'changes', note: 'Client asked for a staged payment schedule.' },
    ],
  },
  {
    id: 'doc-brief-hf',
    title: 'Project brief — identity system',
    type: 'Brief',
    clientId: 'cl-harbor',
    projectId: 'pr-identity',
    workingVersion: 1,
    submittedVersion: 1,
    reviewState: 'approved',
    visibility: 'shared',
    sections: ['Goals', 'Audience', 'Constraints', 'Success criteria'],
    internalNote: '',
    modified: '2026-07-18T10:00:00',
    versions: [{ n: 1, author: 'Nadia Rahman', date: '2026-07-18T10:00:00', decision: 'approved', note: 'Approved at kick-off.' }],
  },
  {
    id: 'doc-welcome-atlas',
    title: 'Welcome pack — Atlas Coffee',
    type: 'Welcome pack',
    clientId: 'cl-atlas',
    projectId: 'pr-packaging',
    workingVersion: 1,
    submittedVersion: 0,
    reviewState: 'draft',
    visibility: 'private',
    sections: ['Next steps', 'Milestones', 'Required inputs'],
    internalNote: 'Do not send until the scope is accepted.',
    modified: '2026-09-08T09:15:00',
    versions: [],
  },
  {
    id: 'doc-proposal-hf',
    title: 'Proposal — website design',
    type: 'Proposal',
    clientId: 'cl-harbor',
    projectId: 'pr-site',
    workingVersion: 1,
    submittedVersion: 1,
    reviewState: 'approved',
    visibility: 'shared',
    sections: ['Context', 'Objectives', 'Scope', 'Schedule', 'Fees'],
    internalNote: '',
    modified: '2026-08-30T14:20:00',
    versions: [
      { n: 1, author: 'Nadia Rahman', date: '2026-08-30T14:20:00', decision: 'approved', note: 'Approved with the phase-two assumption noted.' },
    ],
  },
];

export const seedReviews: Review[] = [
  {
    id: 'rv-1',
    documentId: 'doc-guidelines',
    projectId: 'pr-identity',
    version: 3,
    reviewer: { name: 'Marta Velasco', email: 'marta@harborfinch.com', role: 'Approver' },
    requestedOn: '2026-09-03T10:20:00',
    due: '2026-09-12',
    state: 'waiting',
    outcome: null,
    comments: [
      {
        id: 'cm-1',
        author: 'Marta Velasco',
        date: '2026-09-05T11:30:00',
        body:
          'The clear-space rule reads much better. One question on the reversed wordmark over photography — is there a minimum contrast rule?',
        internal: false,
      },
    ],
  },
  {
    id: 'rv-2',
    documentId: 'doc-guidelines',
    projectId: 'pr-identity',
    version: 2,
    reviewer: { name: 'Marta Velasco', email: 'marta@harborfinch.com', role: 'Approver' },
    requestedOn: '2026-08-19T15:45:00',
    due: '2026-08-26',
    state: 'changes-requested',
    outcome: 'changes',
    closedOn: '2026-08-22T09:10:00',
    supersededBy: 'rv-1',
    comments: [
      {
        id: 'cm-2',
        author: 'Marta Velasco',
        date: '2026-08-22T09:10:00',
        body:
          'Requests changes — we need a wider secondary colour range for the trade-stand work, and the reversed logo needs its own section.',
        internal: false,
      },
    ],
  },
  {
    id: 'rv-3',
    documentId: 'doc-brief-hf',
    projectId: 'pr-identity',
    version: 1,
    reviewer: { name: 'Marta Velasco', email: 'marta@harborfinch.com', role: 'Approver' },
    requestedOn: '2026-07-16T09:00:00',
    due: '2026-07-18',
    state: 'approved',
    outcome: 'approved',
    closedOn: '2026-07-18T10:00:00',
    comments: [],
  },
  {
    id: 'rv-4',
    documentId: 'doc-proposal-verity',
    projectId: 'pr-onboarding',
    version: 1,
    reviewer: { name: 'Anil Kapoor', email: 'anil@verityhealth.io', role: 'Approver' },
    requestedOn: '2026-08-28T13:10:00',
    due: '2026-09-04',
    state: 'changes-requested',
    outcome: 'changes',
    closedOn: '2026-09-02T16:00:00',
    comments: [
      {
        id: 'cm-3',
        author: 'Anil Kapoor',
        date: '2026-09-02T16:00:00',
        body: 'Happy with the scope. Requests changes on payment terms — three milestones rather than two, please.',
        internal: false,
      },
    ],
  },
];

export const seedFiles: ProjectFile[] = [
  { id: 'fl-1', projectId: 'pr-identity', name: 'harbor-finch-logo-package.zip', kind: 'zip', meta: 'ZIP · 18.4 MB', uploaded: '2026-08-12T11:00:00', approved: true },
  { id: 'fl-2', projectId: 'pr-identity', name: 'packaging-artwork-press.pdf', kind: 'pdf', meta: 'PDF · 42.1 MB', uploaded: '2026-09-09T15:20:00', approved: false },
  { id: 'fl-3', projectId: 'pr-identity', name: 'colour-specification-v1.pdf', kind: 'pdf', meta: 'PDF · 240 KB', uploaded: '2026-08-20T09:40:00', approved: true },
  { id: 'fl-4', projectId: 'pr-wayfinding', name: 'signage-system-v4.pdf', kind: 'pdf', meta: 'PDF · 12.1 MB', uploaded: '2026-06-12T10:00:00', approved: true },
  { id: 'fl-5', projectId: 'pr-wayfinding', name: 'installation-drawings-v2.pdf', kind: 'pdf', meta: 'PDF · 8.6 MB', uploaded: '2026-06-14T14:30:00', approved: true },
];

export const seedDeliveries: DeliveryPackage[] = [
  {
    id: 'dl-1',
    projectId: 'pr-identity',
    title: 'Identity system handover',
    recipient: { name: 'Marta Velasco', email: 'marta@harborfinch.com' },
    state: 'missing-approval',
    deliveredOn: null,
    acknowledgedOn: null,
    method: null,
    notes: 'Hold until guidelines v3 is approved. Do not include the motion files.',
    fileIds: ['fl-1', 'fl-3'],
  },
  {
    id: 'dl-2',
    projectId: 'pr-wayfinding',
    title: 'Wayfinding signage system',
    recipient: { name: 'Sofia Brandt', email: 'sofia@lumenarch.com' },
    state: 'delivered',
    deliveredOn: '2026-06-19T15:00:00',
    acknowledgedOn: '2026-06-24T09:40:00',
    method: 'CoreDesk guest link',
    notes: 'Installation drawings at 1:20. Fabricator contact details included.',
    fileIds: ['fl-4', 'fl-5'],
  },
];

export const seedGrants: AccessGrant[] = [
  {
    id: 'gr-1',
    recipient: { name: 'Marta Velasco', email: 'marta@harborfinch.com' },
    role: 'Guest reviewer',
    objectLabel: 'Brand guidelines · v3',
    objectType: 'Review request',
    permissions: ['Read granted version', 'Comment', 'Approve or request changes', 'Download permitted files'],
    state: 'active',
    invited: '2026-09-03T10:15:00',
    lastActivity: '2026-09-05T11:30:00',
    expires: '2026-09-19',
  },
  {
    id: 'gr-2',
    recipient: { name: 'Anil Kapoor', email: 'anil@verityhealth.io' },
    role: 'Guest reviewer',
    objectLabel: 'Proposal — onboarding redesign · v1',
    objectType: 'Review request',
    permissions: ['Read granted version', 'Comment', 'Approve or request changes'],
    state: 'verified',
    invited: '2026-08-28T13:05:00',
    lastActivity: '2026-09-02T16:00:00',
    expires: '2026-09-11',
  },
  {
    id: 'gr-3',
    recipient: { name: 'Sofia Brandt', email: 'sofia@lumenarch.com' },
    role: 'Guest viewer',
    objectLabel: 'Wayfinding signage system',
    objectType: 'Delivery package',
    permissions: ['Read granted content', 'Download permitted files'],
    state: 'revoked',
    invited: '2026-06-19T14:50:00',
    lastActivity: '2026-06-24T09:40:00',
    expires: null,
    revokedOn: '2026-08-15',
  },
  {
    id: 'gr-4',
    recipient: { name: 'Priya Nandakumar', email: 'priya@atlasroasters.co' },
    role: 'Guest reviewer',
    objectLabel: 'Retail packaging range',
    objectType: 'Invitation',
    permissions: ['Read shared project summary'],
    state: 'invited',
    invited: '2026-09-08T09:20:00',
    lastActivity: null,
    expires: '2026-09-22',
  },
  {
    id: 'gr-5',
    recipient: { name: 'Tomas Reiner', email: 'tomas@harborfinch.com' },
    role: 'Guest viewer',
    objectLabel: 'Shared project · Brand identity system',
    objectType: 'Project summary',
    permissions: ['Read approved shared summary', 'Read delivery packages'],
    state: 'expired',
    invited: '2026-07-21T09:00:00',
    lastActivity: '2026-08-02T10:10:00',
    expires: '2026-08-16',
  },
];

export const seedActivity: ActivityEvent[] = [
  {
    id: 'ev-1',
    type: 'feedback',
    actor: 'Marta Velasco',
    date: '2026-09-05T11:30:00',
    title: 'commented on Brand guidelines v3',
    targetLabel: 'Brand guidelines · v3',
    targetHref: '#/documents/doc-guidelines',
    read: false,
    resolves: 'Still needs a decision — a comment does not resolve the review.',
  },
  {
    id: 'ev-2',
    type: 'approved',
    actor: 'Marta Velasco',
    date: '2026-08-30T14:20:00',
    title: 'approved Proposal — website design v1',
    targetLabel: 'Proposal — website design · v1',
    targetHref: '#/documents/doc-proposal-hf',
    read: false,
    resolves: 'Scope acceptance recorded.',
  },
  {
    id: 'ev-3',
    type: 'changes',
    actor: 'Anil Kapoor',
    date: '2026-09-02T16:00:00',
    title: 'requested changes on Proposal — onboarding redesign v1',
    targetLabel: 'Proposal — onboarding redesign · v1',
    targetHref: '#/documents/doc-proposal-verity',
    read: true,
    resolves: 'A revision is required before this can be resubmitted.',
  },
  {
    id: 'ev-4',
    type: 'delivered',
    actor: 'Nadia Rahman',
    date: '2026-06-19T15:00:00',
    title: 'delivered Gallery wayfinding package to Sofia Brandt',
    targetLabel: 'Delivery · Gallery wayfinding',
    targetHref: '#/projects/pr-wayfinding?tab=delivery',
    read: true,
    resolves: 'Acknowledgment pending.',
  },
  {
    id: 'ev-5',
    type: 'acknowledged',
    actor: 'Sofia Brandt',
    date: '2026-06-24T09:40:00',
    title: 'acknowledged the Gallery wayfinding package',
    targetLabel: 'Delivery · Gallery wayfinding',
    targetHref: '#/projects/pr-wayfinding?tab=delivery',
    read: true,
    resolves: 'Acknowledgment is separate from approval.',
  },
  {
    id: 'ev-6',
    type: 'review-requested',
    actor: 'Nadia Rahman',
    date: '2026-09-03T10:20:00',
    title: 'requested review on Brand guidelines v3 from Marta Velasco',
    targetLabel: 'Brand guidelines · v3',
    targetHref: '#/documents/doc-guidelines',
    read: true,
    resolves: 'Waiting on the designated approver.',
  },
];
