packages:
  - "apps/*"
  - "packages/*"
blockExoticSubdeps: false
onlyBuiltDependencies:
  - electron
  - esbuild
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
nodeLinker: hoisted
